#!/usr/bin/env node
/**
 * Concatenates src/*.css into theme.css, in filename order.
 * No dependencies — plain Node.
 *
 *   node build.mjs              build once
 *   node build.mjs --sync       build, then copy into the test vault
 *   node build.mjs --watch      rebuild + sync whenever src/ changes
 */

import {
  readFileSync,
  readdirSync,
  writeFileSync,
  copyFileSync,
  mkdirSync,
  existsSync,
  watch,
} from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const srcDir = join(root, "src");
const outFile = join(root, "theme.css");

/* Vaults to sync into. Override with OBSIDIAN_THEME_DIR (colon-separated for
   more than one). */
const iCloud = join(process.env.HOME, "Library/Mobile Documents");
const VAULT_THEME_DIRS = process.env.OBSIDIAN_THEME_DIR
  ? process.env.OBSIDIAN_THEME_DIR.split(":")
  : [
      join(iCloud, "com~apple~CloudDocs/TestVault/.obsidian/themes/Cairn"),
      join(iCloud, "iCloud~md~obsidian/Documents/BlinkObsidianVault/.obsidian/themes/Cairn"),
    ];

const manifest = JSON.parse(readFileSync(join(root, "manifest.json"), "utf8"));

function build() {
  const files = readdirSync(srcDir).filter((f) => f.endsWith(".css")).sort();

  const banner = `/*
 * ${manifest.name} v${manifest.version} — ${manifest.author}
 * Generated from src/ by build.mjs. Do not edit this file directly.
 */\n\n`;

  const body = files
    .map((f) => readFileSync(join(srcDir, f), "utf8").trimEnd())
    .join("\n\n");

  writeFileSync(outFile, banner + body + "\n");
  return files.length;
}

function sync() {
  const done = [];
  for (const dir of VAULT_THEME_DIRS) {
    /* Only sync into vaults that exist — never create a stray vault. */
    if (!existsSync(join(dir, "../.."))) continue;
    mkdirSync(dir, { recursive: true });
    copyFileSync(outFile, join(dir, "theme.css"));
    copyFileSync(join(root, "manifest.json"), join(dir, "manifest.json"));
    done.push(dir.replace(process.env.HOME, "~"));
  }
  return done;
}

function run() {
  const n = build();
  let msg = `built theme.css from ${n} module(s)`;
  if (process.argv.includes("--sync") || process.argv.includes("--watch")) {
    const done = sync();
    msg += done.length ? `\n  → ${done.join("\n  → ")}` : " (no vault found to sync)";
  }
  console.log(`[${new Date().toLocaleTimeString()}] ${msg}`);
}

run();

if (process.argv.includes("--watch")) {
  console.log("watching src/ and manifest.json …");
  let timer;
  const debounced = () => {
    clearTimeout(timer);
    timer = setTimeout(run, 80);
  };
  watch(srcDir, debounced);
  watch(join(root, "manifest.json"), debounced);
}
